(#205) fixed timer handling in validateResult
nut-tree/nut.js pull request #206
Opened 2021-01-25 15:30 UTC by svettwer

fixes #205

2021-01-31 17:45 UTC, s1hofmann requested changes
Thanks for the fix. I left some remarks on the test and found some chores to do :)

2021-01-31 17:45 UTC, s1hofmann commented on lib/util/poll-action.function.spec.ts
> +        }
After re-reading the test suite I noticed this repeated pattern which could be refactored into something like


```ts
// WHEN
const SUT = () => timeout(updateInterval, maxDuration, action);

// THEN
await expect(SUT).rejects.toBe(`Action timed out after ${maxDuration} ms`);
```

2021-01-31 17:45 UTC, s1hofmann commented on lib/util/poll-action.function.spec.ts
> +        }, 500);
If we want to make sure that `action` is only executed once the initial `expect` is superfluous, isn't it?

2021-02-01 11:01 UTC, svettwer commented on lib/util/poll-action.function.spec.ts
> +        }, 500);
From my perspective, this is required. As this is a `setTimeout` leak, I want to make sure that a call has hit the mock before we wait a certain time. And after we waited, I want to ensure that no other call occurred. 
In theory, the first check would not be required. But we often recognized strange timing behaviors on build agents where timeouts fired much later than they should, producing fase positive as well as false negative test results. This should just harden the test result.

2021-02-01 11:02 UTC, svettwer commented on lib/util/poll-action.function.spec.ts
> +        }
Agreed. Is this something to resolve in this PR? It could be refactored but does not add any additional value to the code.

2021-02-04 20:20 UTC, s1hofmann commented on lib/util/poll-action.function.spec.ts
> +        }
> Is this something to resolve in this PR? It could be refactored but does not add any additional value to the code.

I didn't intend to sound nitpicky. It's just that I recognised a possible improvement (to get rid of one of my code smells).
You know, boyscouts and all that stuff...

2021-02-04 20:21 UTC, s1hofmann approved these changes

2021-02-05 07:25 UTC, merged