(#202) Install @nut-tree/libnut@next
nut-tree/nut.js pull request #207
Opened 2021-01-25 21:59 UTC by s1hofmann

2021-01-27 07:42 UTC, svettwer requested changes

2021-01-27 07:42 UTC, svettwer commented on .github/workflows/snapshot_release.yaml
> +        run: npm i @nut-tree/libnut@next
Is it intended to only install `@nut-tree/libnut@next` in the `test` job?
As the changes are not committed as far as I can see, the checkout action in line 45 would not consider the change.
In addition, even if a publish would consider `@nut-tree/libnut@next` it would fail from my perspective as the installation during the ci process would change the `package-lock.json` and publishing with uncommitted changes is not allowed. To be honest, I'm not sure if there is a switch to change that. :thinking: 

I'd recommend to add the next version of libnut to the package.json instead of installing it during CI.

2021-01-27 09:18 UTC, s1hofmann commented on .github/workflows/snapshot_release.yaml
> +        run: npm i @nut-tree/libnut@next
> Is it intended to only install @nut-tree/libnut@next in the test job?

Argh, too many jobs I recently updated. No, that went unnoticed.

> during the ci process would change the package-lock.json and publishing with uncommitted changes is not allowed

`package-lock.json` files are never published, so that's no problem.

2021-01-28 12:11 UTC, svettwer approved these changes

2021-01-28 12:13 UTC, svettwer commented on .github/workflows/snapshot_release.yaml
> +        run: npm i @nut-tree/libnut@next
hmhmh :thinking: 
you could just add the following to `package.json`

```json
  "dependencies": {
    "@nut-tree/libnut": "next",
    "clipboardy": "2.0.0",
    "opencv4nodejs-prebuilt": "5.3.0-2"
  },
```

if the next version is tagged correctly, no further info is required.

2021-01-31 15:01 UTC, merged